# Generated by Django 2.2.4 on 2020-08-05 11:50

from django.db import migrations, models
import doubtapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=20)),
                ('Ques_ID', models.CharField(max_length=6)),
                ('Q_Type', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank='True', upload_to=doubtapi.models.get_upload_path)),
            ],
        ),
    ]
